edition = "2021"
version = "Two"
unstable_features = true

hard_tabs = true

max_width = 100
use_small_heuristics = "Max"
chain_width = 50
single_line_let_else_max_width = 0
struct_lit_width = 80

imports_granularity = "One"
group_imports = "StdExternalCrate"
reorder_modules = false

brace_style = "PreferSameLine"
condense_wildcard_suffixes = true
empty_item_single_line = false
format_macro_matchers = true
newline_style = "Unix"
overflow_delimited_expr = true
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true
